### ISSUE TITLE
Difference between final_split_non_voc_instances_train2017.json and your log file

### ISSUE THREAD

**Issue by GuangxingHan** [fanq15/FewX#15]
I follow the step 2 to generate final_split_non_voc_instances_train2017.json. The result dataset is slightly different to you training log. I am wondering whether I missed something? Thanks.

`|   category    | #instances   |   category   | #instances   |   category    | #instances   |
|:-------------:|:-------------|:------------:|:-------------|:-------------:|:-------------|
|    person     | 0            |   bicycle    | 0            |      car      | 0            |
|  motorcycle   | 0            |   airplane   | 0            |      bus      | 0            |
|     train     | 0            |    truck     | 4483         |     boat      | 0            |
| traffic light | 1545         | fire hydrant | 1172         |   stop sign   | 1130         |
| parking meter | 511          |    bench     | 3977         |     bird      | 0            |
|      cat      | 0            |     dog      | 0            |     horse     | 0            |
|     sheep     | 0            |     cow      | 0            |   elephant    | 4007         |
|     bear      | 1241         |    zebra     | 4090         |    giraffe    | 4481         |
|   backpack    | 2632         |   umbrella   | 3634         |    handbag    | 3029         |
|      tie      | 2666         |   suitcase   | 3102         |    frisbee    | 1343         |
|     skis      | 2570         |  snowboard   | 1296         |  sports ball  | 848          |
|     kite      | 1327         | baseball bat | 996          | baseball gl.. | 749          |
|  skateboard   | 2922         |  surfboard   | 3377         | tennis racket | 1693         |
|    bottle     | 0            |  wine glass  | 2069         |      cup      | 6270         |
|     fork      | 2498         |    knife     | 2743         |     spoon     | 2037         |
|     bowl      | 5207         |    banana    | 3753         |     apple     | 2231         |
|   sandwich    | 2972         |    orange    | 2765         |   broccoli    | 4347         |
|    carrot     | 2964         |   hot dog    | 1829         |     pizza     | 3846         |
|     donut     | 4160         |     cake     | 3422         |     chair     | 0            |
|     couch     | 0            | potted plant | 0            |      bed      | 3005         |
| dining table  | 0            |    toilet    | 3464         |      tv       | 0            |
|    laptop     | 2289         |    mouse     | 918          |    remote     | 1480         |
|   keyboard    | 1351         |  cell phone  | 2602         |   microwave   | 670          |
|     oven      | 1346         |   toaster    | 73           |     sink      | 2858         |
| refrigerator  | 1271         |     book     | 3823         |     clock     | 2682         |
|     vase      | 2982         |   scissors   | 968          |  teddy bear   | 3386         |
|  hair drier   | 119          |  toothbrush  | 783          |               |              |
|     total     | 148004       |              |              |               |              |
`

**Comment by fanq15** [comment]
I fixed a small bug in the step 2 script which will not affect the performance.

**Comment by GuangxingHan** [comment]
Thanks
