### ISSUE TITLE
training end with AssertionError

### ISSUE THREAD

**Issue by MARMOTatZJU** [fanq15/FewX#3]
Both basic training and finetuning end with AssertionError thrown from [this line](https://github.com/fanq15/FewX/blob/0e79587d0f91919b8b77737e2de545eb107c5d2f/fewx/modeling/fsod/fsod_rcnn.py#L303). Does this mean that training ends correctly?

**Comment by fanq15** [comment]
Yes, it ends correctly. It first generates the offline support features and then uses it to detect images. I will add more comment.

**Comment by MARMOTatZJU** [comment]
Ok I see your latest commit. Support feature's path is now correct. Thanks for your reply.
