### ISSUE TITLE
I get AP 11.45. How to get AP 12?

### ISSUE THREAD

**Issue by w39865008** [fanq15/FewX#39]
Hi，我在不同机器训练了两次，一次得到了11.45%的准确率，一次是11.40%，请问这个训练结果是不稳定吗，应该怎么得到 12% 的 AP 呢

[fsod_train_log.txt](https://github.com/fanq15/FewX/files/6236830/fsod_train_log.txt)
[fsod_finetune_test_log.txt](https://github.com/fanq15/FewX/files/6236834/fsod_finetune_test_log.txt)
[fsod_finetune_train_log.txt](https://github.com/fanq15/FewX/files/6236835/fsod_finetune_train_log.txt)

**Comment by Zhang1Sheng** [comment]
您好，我这边出现了一个参数报错的问题，是在fsod_roi_heads.py文件中，在_build_res5_block创建block时，因为first_stride这个参数报错。希望您能够帮忙解决一下问题，这是我的email：1434012475@qq.com
![Uploading PQMRE`9FTZHCP[4AE7}}WVO.png…]()

**Comment by Zhang1Sheng** [comment]
![PQMRE`9FTZHCP 4AE7}}WVO](https://user-images.githubusercontent.com/51778165/114018090-72500180-989f-11eb-8097-26dad330542b.png)

**Comment by Zhang1Sheng** [comment]
![5JG6F2IO76BURVEO~251RB](https://user-images.githubusercontent.com/51778165/114018175-8a278580-989f-11eb-9f7a-7ecfe59d50ba.png)

**Comment by Zhang1Sheng** [comment]
> Hi，我在不同机器训练了两次，一次得到了11.45%的准确率，一次是11.40%，请问这个训练结果是不稳定吗，应该怎么得到 12% 的 AP 呢
> 
> [fsod_train_log.txt](https://github.com/fanq15/FewX/files/6236830/fsod_train_log.txt)
> [fsod_finetune_test_log.txt](https://github.com/fanq15/FewX/files/6236834/fsod_finetune_test_log.txt)
> [fsod_finetune_train_log.txt](https://github.com/fanq15/FewX/files/6236835/fsod_finetune_train_log.txt)

![(FNMNJ28(96TBAT}RV1 4K](https://user-images.githubusercontent.com/51778165/114492535-5a83cf00-9c4b-11eb-9bc8-5bfd9dd74c75.png)
I know that the model generates 100 BBoxes for each class, but when I predicted that only dozens of BBoxes were generated for each class. Why not 100 and how to solve this problem?Could  you help me out?

**Comment by fanq15** [comment]
Hi, the testing performance is not stable. It is normal to get 11.4%. The reported performance in this repo is the best performance. You can refer to the performance in our paper for comparison.
