### ISSUE TITLE
FSYTV-40-images is a 149bite file, no image data 

### ISSUE THREAD

**Issue by wpfhtl** [fanq15/FewX#52]
When I try to download the FSYTV-40-images from this link, https://drive.google.com/drive/folders/1a1PpfAxeYL7AbxYViDDnx7ACFtRohVL5, it shows the FSYTV-40-images is a 149bite file, no image data.

**Comment by fanq15** [comment]
Yes. You should go to the Youtube-VIS webpage to download the images. We use their images and split the annotation json file for few-shot learning.
