### ISSUE TITLE
fsod_fast_rcnn.py中，在将背景的logit进行排序时，为什么选用的是第0列而不是第1列？

### ISSUE THREAD

**Issue by Zhang1Sheng** [fanq15/FewX#57]
![B`OFR)%@U(WWZ41NB7 TBZ7](https://user-images.githubusercontent.com/51778165/127279601-64374b1d-ab3f-4be8-a9a5-0b25794a02f3.png)

**Comment by fanq15** [comment]
Because the first column is for the background.
